### ISSUE TITLE
Capitalise SU2C headings

### ISSUE THREAD

**Issue by eardenercruk** [CRUKorg/cruk-react-components#197]
SU2C brand requires all-caps headings, so text should be transformed for SU2C theme

**Comment by Develliot** [comment]
Good shout do we have any links to any design files that we could use as a ref

**Comment by eardenercruk** [comment]
> Good shout do we have any links to any design files that we could use as a ref

@Develliot 
https://xd.adobe.com/view/013e4a59-7fb5-4de5-aa19-37d9a824f630-546d/screen/9e79e781-f25e-4e11-8c90-023e6a10a461/
https://xd.adobe.com/view/b70ff390-dd64-45cb-b0a8-aee1d1e06074-e25c/

**Comment by Develliot** [comment]
fixed
