### ISSUE TITLE
Failing font file requests

### ISSUE THREAD

**Issue by eardenercruk** [CRUKorg/cruk-react-components#225]
![image](https://user-images.githubusercontent.com/57360840/109782707-15f32580-7c01-11eb-80d9-d9b623e6244b.png)

Suggested fix:
Specify which formats are available in the customFonts object in the theme file.

**Comment by eardenercruk** [comment]
Linked to issue in Payments https://github.com/CRUKorg/cruk_online_payments/issues/1776

**Comment by Develliot** [comment]
This is another reason why I would like us to have our own CDN for the component lib, So I can upload assets and deal with these problems.

I think we have woff and woff2 as browser compatibility thing so I think IE11 can't handle woff2, however I think woff2 is 30% smaller so is preferable.

Is this actually breaking stuff for you? Or is it just getting woff2 and failing on woff?

**Comment by eardenercruk** [comment]
@Develliot OK looks like this is a stupid Windows laptop thing - could you do me a favour and have a look on your mac which font is loaded here? https://app.pws.int.cruk.org/support-us/your-donation
I'd expect the woff2 and no console errors...

**Comment by Develliot** [comment]
![Uploading Screenshot 2021-03-03 at 09.39.35.png…]()

**Comment by Develliot** [comment]
![Screenshot 2021-03-03 at 09 39 35](https://user-images.githubusercontent.com/5347198/109785899-83548580-7c04-11eb-9b54-5e74d6e160f0.png)

**Comment by Develliot** [comment]
![Screenshot 2021-03-03 at 09 43 03](https://user-images.githubusercontent.com/5347198/109786234-df1f0e80-7c04-11eb-8f4f-f35543205a16.png)
 I also get the google roboto font too for some reason

**Comment by eardenercruk** [comment]
OK yeah the woff2 is my bad. The console error does appear to be an issue on Windows laptops with the ccp-s3.int.cruk.org domain. We also have issues with pws.int, so this isn't anything new. Closing as not really the CL's problem.
