### ISSUE TITLE
Component Library Button "secondary" hover state causes accessibility error

### ISSUE THREAD

**Issue by juff** [CRUKorg/cruk-react-components#299]
`'color-contrast' │ 'serious' │ 'Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds'`

When running cypress-axe accessibility checks Button Secondary highlights a color-contrast error

**Comment by juff** [comment]
@carlos-cruk  or @RichSCRUK  any suggestions for an updated hover background-color for secondary Button to make it accessible?

**Comment by carlos-cruk** [comment]
Not too concerned with the colour contrast on a button that the user has already read, found and is about to click on. I'm going to double-check with Rich on this, but I believe that hover states aren't in the strict AA guideline requirements.

**Comment by juff** [comment]
@carlos-cruk and @RichSCRUK  This issue was bought up as I am using the CL library components in the payments (PWS) and it has been raised as a bug. Should i say this is an issue that won't be fixed.
