### ISSUE TITLE
Fix Gallery Arrows

### ISSUE THREAD

**Issue by jackso-bytes** [CRUKorg/cruk-react-components#558]
There is a size difference in gallery next/previous arrows in Firefox 102 and Safari 15.5 on macOS. 
![_thumb_61386](https://user-images.githubusercontent.com/5347198/189090841-17324a5b-08fd-4ee9-96ac-795a258def05.png)

**Comment by Develliot** [comment]
looks like some unicode issue, lets use FaIcons instead for consistency
