### ISSUE TITLE
Checkbox disabled styles

### ISSUE THREAD

**Issue by JanGanaCode** [CRUKorg/cruk-react-components#675]
This might be intentional but the disabled styles for the checkbox differ from other inputs:

![Screenshot 2023-04-24 at 17 12 19](https://user-images.githubusercontent.com/25926950/234242464-bb3ea6ab-0516-40de-975a-79f82e05695f.png)

Maybe should look like this (?):
![Screenshot 2023-04-24 at 17 13 32](https://user-images.githubusercontent.com/25926950/234242471-35039636-7767-4648-9b16-5c89ac6d62ef.png)

**Comment by samkio** [comment]
I agree it should be consistent. @Develliot do you if there is a reason why the checkbox differs? Can we make this fix?
